cask_args appdir: '/Applications'

tap 'caskroom/cask'
tap 'caskroom/fonts'
tap 'thoughtbot/formulae'

brew 'coreutils'
brew 'git'
brew 'go'
brew 'ivy'
brew 'python'
brew 'mackup'
brew 'maven'
brew 'rcm'
brew 'rpm'
brew 'sbt'
brew 'scala'
brew 'vim'
brew 'wget'
brew 'zsh'

cask '1password'
cask 'airserver'
cask 'alfred'
cask 'atom'
cask 'backblaze'
cask 'cleanmymac'
cask 'docker'
cask 'dropbox'
cask 'firefox'
cask 'garmin-express'
cask 'google-chrome'
cask 'intellij-idea'
cask 'istat-menus'
cask 'iterm2'
cask 'java'
cask 'microsoft-office'
cask 'omnigraffle'
cask 'robomongo'
cask 'slack'
cask 'transmission'
cask 'transmit'

cask 'font-inconsolata'
cask 'font-source-code-pro'
