cask_args appdir: '/Applications'

tap 'caskroom/cask'
tap 'caskroom/fonts'
tap 'thoughtbot/formulae'
tap 'buo/cask-upgrade'

brew 'coreutils'
brew 'gdbm'
brew 'git'
brew 'go'
brew 'hadoop'
brew 'ivy'
brew 'kafka'
brew 'python'
brew 'mackup'
brew 'mas'
brew 'maven'
brew 'openssl'
brew 'rbenv'
brew 'rcm'
brew 'rpm'
brew 'ruby'
brew 'sbt'
brew 'scala'
brew 'tig'
brew 'vim'
brew 'wget'
brew 'zookeeper'
brew 'zsh'

cask_args appdir: '/Applications'
cask 'airserver'
cask 'alfred'
cask 'atom'
cask 'backblaze'
cask 'cleanmymac'
cask 'carbon-copy-cloner'
cask 'colloquy'
cask 'docker'
cask 'dropbox'
cask 'firefox'
cask 'garmin-express'
cask 'google-chrome'
cask 'intellij-idea'
cask 'istat-menus'
cask 'iterm2'
cask 'java'
cask 'jce-unlimited-strength-policy'
cask 'logitech-options'
cask 'microsoft-office'
cask 'omnigraffle'
cask 'quickbooks'
cask 'robomongo'
cask 'slack'
cask 'steam'
cask 'transmission'
cask 'visualvm'

cask 'font-inconsolata'
cask 'font-source-code-pro'

mas '1Password', id: 443987910
mas 'Keynote', id: 409183694
mas 'Numbers', id: 409203825
mas 'Pages', id: 409201541
mas 'Transmit', id: 403388562
mas 'Tweetbot', id: 557168941
mas 'Xcode', id: 497799835
