cask_args appdir: '/Applications'

tap 'caskroom/cask'
tap 'caskroom/drivers'
tap 'caskroom/fonts'

cask 'java'

brew 'awscli'
brew 'coreutils'
brew 'gdbm'
brew 'git'
brew 'go'
# brew 'kubernetes-helm'
# brew 'ivy'
brew 'jq'
brew 'lua@5.1'
brew 'python3'
brew 'mackup'
brew 'mas'
brew 'maven'
brew 'mercurial'
brew 'nats-streaming-server'
brew 'npm'
brew 'openssl'
brew 'pandoc'
brew 'postgres'
brew 'prometheus'
brew 'rbenv'
brew 'redis'
brew 'rpm'
brew 'ruby'
brew 'sbt'
brew 'scala'
brew 'tig'
brew 'vim'
brew 'zsh'
brew 'zsh-completions'

cask '1password'
cask 'airserver'
cask 'alfred'
cask 'backblaze'
cask 'cleanmymac'
cask 'carbon-copy-cloner'
cask 'docker'
cask 'dropbox'
cask 'garmin-express'
cask 'google-chrome'
cask 'istat-menus'
cask 'iterm2'
cask 'jetbrains-toolbox'
cask 'mactex'
cask 'microsoft-office'
cask 'omnigraffle'
cask 'slack'
cask 'tunnelblick'
cask 'visualvm'
cask 'visual-studio-code'
cask 'vlc'

cask 'font-source-code-pro'

mas 'Keynote', id: 409183694
mas 'Numbers', id: 409203825
mas 'Pages', id: 409201541
mas 'Transmit', id: 403388562
mas 'Tweetbot', id: 557168941
mas 'Xcode', id: 497799835
