#!/bin/sh

if [ ! -e $HOME/.vim/autoload/plug.vim ]; then
  curl -fLo $HOME/.vim/autoload/plug.vim --create-dirs https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim
fi
vim -u $HOME/.vimrc.bundles +PlugInstall +PlugClean! +qa

ln -s ~/Dropbox/System/ssh-config ~/.ssh/config
ln -s ~/Dropbox/System/jbailey.keytab ~/jbailey.keytab
sudo ln -s ~/Dropbox/System/krb5.conf /etc/krb5.conf
